site_name: openpaimarketplace
repo_url: https://github.com/microsoft/openpaimarketplace
repo_name: openpaimarketplace
nav:
  - Home: index.md
  - User Manual:
      - Introduction: user/README.md
      - Quick Start: user/quick-start.md
      - Data Management: user/data-management.md
      - Create Template: user/create-template.md
  - Admin Manual:
      - Introduction: admin/README.md
      - Deployment: deployment.md
  - Deployment: deployment.md
  - Getting Started: getting_started.md
theme: readthedocs
